# Workflow for running backend tests for PRs and main branch

name: Backend Tests

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'src/**'

defaults:
  run:
    working-directory: src

jobs:
  # Runs pytest for backend code
  tests:
    name: pytest
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        working-directory: src
        run : python -m pytest
