name: Deploy Changes to Cluster

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  prod:
    name: deploy to production
    runs-on: ubuntu-latest
    if: github.repository == 'napari/napari' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Deploy Changes
        run: |
          sudo scripts/happy --env prod update prod
  staging:
    name: deploy to staging
    runs-on: ubuntu-latest
    if: github.repository == 'napari/napari' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Deploy Changes
        run: |
          sudo scripts/happy --env staging update staging

